### ISSUE TITLE
Alarm Triggered Issue

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#1]
HomeKit does not seem the know when the Alarm is trigged (ie Siren of going off).

```
[4/27/2020, 15:59:56] [RiscoAlarm] Session Expired. ReLogin
[4/27/2020, 15:59:56] [RiscoAlarm] Logged In Cloud
[4/27/2020, 17:00:26] [RiscoAlarm] Session Expired. ReLogin
[4/27/2020, 17:00:27] [RiscoAlarm] Logged In Cloud
[4/27/2020, 18:00:56] [RiscoAlarm] Session Expired. ReLogin
[4/27/2020, 18:00:56] [RiscoAlarm] Logged In Cloud
[4/27/2020, 18:30:06] [RiscoAlarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
```
the alarm was trigged at 18:29 ish. can you try to debug it.

```
Event Alarm - 'Garage', 'Garage Door' occurred at your system at 27/04/2020 18:29:00 

Kindest regards,
<Risco Cloud>
```

**Comment by gawindx** [comment]
Indeed, it is a (small) oversight on my part.
I'm working on it to solve the problem.
I publish as soon as I have a viable solution.

**Comment by andyblac** [comment]
Cheers bud

**Comment by gawindx** [comment]
The code has been updated and should work properly.
By the way, the npm is now available (it contains these latest modifications).
It can therefore be installed instead.

the npm is named: "homebridge-risco-platform"

**Comment by andyblac** [comment]
thanks, got it loaded. i'll report back when tested.

**Comment by andyblac** [comment]
it seem 'Triggered' still dose not work, cn you recheck it ?

![IMG_0127](https://user-images.githubusercontent.com/77936/86930714-37157c00-c12f-11ea-9310-f1bbe495e7a6.jpeg)

**Comment by gawindx** [comment]
Can you tell me if this problem still seems relevant to you? or if the operation seems correct to you?

**Comment by andyblac** [comment]
hi, it does now report that alarm has been triggered, but once it has been triggered, the set screen is shown as 'OFF', so to actually turn off the the alarm in homekit, you have to 1st choose AWAY, then OFF. can you fix this ?

**Comment by gawindx** [comment]
i think it should now work fine
