### ISSUE TITLE
Getting an error while trying to arm the alarm

### ISSUE THREAD

**Issue by ghost** [gawindx/homebridge-risco-platform#12]
**These are my settings-**
{
    "Outputs": "all",
    "name": "Risco Alarm",
    "riscoUsername": "XXX",
    "Groups": "all",
    "Detectors": "all",
    "polling": true,
    "platform": "RiscoAlarm",
    "pollInterval": 10000,
    "riscoPassword": "XXX",
    "riscoSiteId": XXX,
    "riscoPIN": "XXX",
    "Partition": "all"
}
_i put XXX where my real info is_

**This is the log-**
10.9.2020, 19:00:04 [Risco Alarm] Error on getGroupsStates: TypeError: Cannot read property 'actualState' of undefined
    at RiscoPanelSession.getGroupsStates (/home/hoobs/.hoobs/node_modules/homebridge-risco-platform/Risco.js:1034:109)
    at RiscoPanelSession.UpdateCPStates (/home/hoobs/.hoobs/node_modules/homebridge-risco-platform/Risco.js:1175:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
10.9.2020, 19:00:04 [Risco Alarm] Error on UpdateCPStates: undefined
10.9.2020, 19:00:04 (node:6276) UnhandledPromiseRejectionWarning: undefined
10.9.2020, 19:00:04 (node:6276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)

**Comment by gawindx** [comment]
I take note of the problem.

Just to be sure, did this error occur at the time of connection or later?
I know that it can sometimes happen that at the time of connection the request does not return the expected values.
I normally set up a check that prevents this but it may be flawed.

**Comment by gawindx** [comment]
Disregard my previous question, you specify that it is when arming, so it has nothing to do with a bad request when starting the plugin.

**Comment by ghost** [comment]
You rock man!
thx for the super fast attention
hope u can find time to help in the matter

**Comment by gawindx** [comment]
Problem identified and solved.
The fix will be available in the next release.

**Comment by gawindx** [comment]
the npm package is updated to v1.1.6 and contains this fix.
I close the issue, do not hesitate to reopen it if necessary
