### ISSUE TITLE
in the latest version we have 'Switches' show in status.

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#17]
this is confusing, can we hide please?
![IMG_0351](https://user-images.githubusercontent.com/77936/96632433-99c20a80-130f-11eb-9853-c3aff78074df.jpeg)
![IMG_0352](https://user-images.githubusercontent.com/77936/96632436-9af33780-130f-11eb-8cc2-807ec7abf0a6.jpeg)

**Comment by andyblac** [comment]
also what are they suposed to do ?, as if i turn say Door off, and leave homekit and come back in, it is back ON.

**Comment by andyblac** [comment]
ok, i see, it Disables Detector, but it only works if alarm is "Disabled", is there no way to "lock" switch is alarm is "Enabled"

**Comment by gawindx** [comment]
yes, the switches are used to exclude the sensors.

it does not seem to me that the old version of homekit indicated a synthesis at the top of the screen as is the case now which can be a little disturbing, in any case it is my opinion even if for some accessories this can be practical.

if you click on a sensor, you will have the switch corresponding to the sensor only.
![983D2631-96B2-41D9-A23C-5C6261572AA8](https://user-images.githubusercontent.com/10830959/96638744-e6621180-1320-11eb-9c07-f72bb47e5484.jpeg)

concerning the exclusion itself, one cannot exclude an armed sensor; it is also a temporary exclusion in the sense that the exclusion will be valid until the next disarming (it does not depend on homebridge but on the control panel itself and this operation is valid on most systems).

When has your suggestion, I had not thought of it but indeed it would be more judicious.

**Comment by gawindx** [comment]
it is normally no longer possible to exclude a sensor in an armed partition.
