### ISSUE TITLE
alarm set in Scenes

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#19]
when we use set alarm in a scene, and the alarm is already set, it unsets the alarm and resets it. even though the target state was the same, this can casue issue when we use automations based on Alarm state.

so, Could you add a check before setting the Target state, that it does not equal the Current Set state.

i.e
1: alarm is set for "Away"
2: a scene has the Alarm to set to "Away"
3: run the scene, the alarm will unset, and then reset to "away". it should IMO it should just ignore the the action.

**Comment by gawindx** [comment]
I reassure you, this feature is well planned, but I needed to set up other elements to lean on it (such as the occupancy sensor which will provide me with this information).

I also needed to deploy it to see any feedback before going too far.

**Comment by gawindx** [comment]
version 1.1.7 should correct the problem.

**Comment by gawindx** [comment]
it is normally no longer possible to exclude a sensor in an armed partition.

**Comment by andyblac** [comment]
thx
