### ISSUE TITLE
Can't seem to arm/disarm, or any other action...PLEASE HELP!

### ISSUE THREAD

**Issue by ghost** [gawindx/homebridge-risco-platform#20]
Config:
{
    "platform": "RiscoAlarm",
    "name": "RiscoAlarm",
    "riscoUsername": "XXXXXX",
    "riscoPassword": "XXXXX",
    "riscoSiteId": XXXXXX,
    "riscoPIN": "XXXX",
    "polling": true,
    "pollInterval": 10000,
    "Partition": "all",
    "armCommand": "armed",
    "partialCommand": "disarmed",
    "homeCommand": "disarmed",
    "disarmCommand": "disarmed",
    "Groups": "all",
    "Outputs": "all",
    "Detectors": "all",
    "Custom": {
        "Door": "14,15",
        "Contact Sensor": "12,18,17",
        "Window": "10,11,13,19,23,24"
    }
}

Log:
[10/22/2020, 08:46:55] [RiscoAlarm] Error on Get Partitions States: TypeError: Cannot read property 'detectors' of undefined
    at RiscoPanelSession.getPartsStates (/usr/local/lib/node_modules/homebridge-risco-platform/Risco.js:1158:94)
    at RiscoPanelSession.UpdateCPStates (/usr/local/lib/node_modules/homebridge-risco-platform/Risco.js:1353:28)
    at RiscoPanelSession.getCPStates (/usr/local/lib/node_modules/homebridge-risco-platform/Risco.js:1334:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[10/22/2020, 08:46:55] [RiscoAlarm] Error on UpdateCPStates: undefined
(node:3612) UnhandledPromiseRejectionWarning: undefined
(node:3612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 804)

**Comment by gawindx** [comment]
this problem can sometimes happen when starting the plugin (cannot read property 'x' of undefined)
the riscoCloud sometimes returns bad info and the initialization goes badly.
it's random and I have to improve the process at this level.

in this case, the easiest way is to restart homebridge and that should solve the problem (provided that all the connection information is obviously correct)

**Comment by ghost** [comment]
Thx for the quick reply! really appreciate your work.

The connection info is correct, i do get the detectors and all other info into the home app.
I have done a lot of restarts this past week (updating config for other plug ins and all) and this error keeps on showing on my log, can't really use the plugin for actions...

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/70616838/96833461-26241880-1449-11eb-809b-f6f082438909.png)
this is my log from few seconds ago

**Comment by gawindx** [comment]
clearly, you seem to be facing a different problem than the one I was thinking of.

I unfortunately cannot give you more help immediately, at least not until tonight.

I see this in more detail as soon as I get home

**Comment by gawindx** [comment]
I think I fixed the problem, and it looks like it came from my code.

Can you test by getting the "Risco.js" file from the git to test before the patch is released?

**Comment by ghost** [comment]
Hi, sorry but i do not know how to do this...
i only know how to update the plugin in the homebridge UI

**Comment by gawindx** [comment]
version 1.1.7 must correct the problem, in addition to some improvements (not visual, so no change on the service side or other)

**Comment by ghost** [comment]
you right!
everything is running perfectly now, thank a lot!

**Comment by gawindx** [comment]
ok, I close the issue
