### ISSUE TITLE
Outputs shown as Switches

### ISSUE THREAD

**Issue by kellery82** [gawindx/homebridge-risco-platform#22]
Hi,

I have three outputs (Garage 1, 2 and 3) on my alarm which trigger the garage doors to open. As they are shown as switches, if i want Siri to open or close the door i have to say Garage 1 On. This is probably more of an enhancement than an issue - is there any way to make it a door as opposed to a switch?

I also have reed switches on the doors, I noticed in the to do list that there might be the future possibility of combining this with the outputs to detect whether the door is open or closed - this would be really handy.

Thanks in advance,

Kristopher

**Comment by gawindx** [comment]
Thank you for this feedback.

I'm in the same case as you, my garage door can be controlled from my control unit and it is also monitored by a contact.
It is exactly for this purpose that I plan to give this possibility of creating accessories combining both an entrance and an exit.
I think this is the best solution to easily handle this kind of case.
To date, I think my code has reached a certain stability and maturity which were both necessary before embarking on the development of this feature; which means that, less than a setback, this option should be the next to emerge.
The "garage door" accessory will of course be part of the first version, as will the door and window.

Regarding the outputs alone, I think I would not make any changes to the operation, at least not immediately.
The problem at the level of the outputs only and that it would be necessary to indicate a rather large number of different type of customization and that I am afraid that by force, the configuration of the platform will become very complex or illegible in the case of certain installations.

**Comment by kellery82** [comment]
Thanks gawindx. I look forward to the new feature. Your work is much appreciated.

**Comment by gawindx** [comment]
The v1.2.0 brings the possibility of creating combined accessories.

This should allow you to create a "Garage Door Opener" accessory that will contain both the door control as well as an input that will tell you the status of your door.

**Comment by gawindx** [comment]
I think this problem is no longer relevant, I close the issue but it can be reopened if necessary
