### ISSUE TITLE
Ocupancy issue with diferant Zones

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#24]
if a 'Occupancy' sensor is active it will not let you set/unset the Alarm from a differant zone.

ie
Zone1:
Door is open, thus 'Ocupancy' is detected.

you can't unset the Alarm in Zone2.

**Comment by gawindx** [comment]
I take note and, to be honest, this functionality does not suit me completely as it is.
It's more than likely that I'll turn it off in the next update to develop something that will suit me better.

I also noticed some difficulties with the arming due to this function, which led me to make this decision.

**Comment by gawindx** [comment]
The latest version (1.2.0) benefits from a revised and improved code concerning occupancy sensors.

Regarding the specific problem you encounter, I have not managed to reproduce it neither before nor after modifying the code.

However, I added an option in the platform config which allows to deactivate the occupancy check before authorizing or not the arming / disarming.
It could as well be used to simply deactivate the functionality as to prevent it from posing a problem if necessary.

**Comment by andyblac** [comment]
same issue in latest version, i have just disabled occupancy thing. thx

**Comment by gawindx** [comment]
I cannot reproduce the problem you are having, so I cannot find a workaround.

For the next version, I will provide you a file (or a specific update) with a lot of logging on this part of the operation to try to understand and make this function work correctly.

**Comment by gawindx** [comment]
This issue is closed due to the stop of the development of the plugin.
For more information, see [here](https://github.com/gawindx/homebridge-risco-platform/issues/45)
