### ISSUE TITLE
Error on Get Partitions States : TypeError : Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Sylanorr** [gawindx/homebridge-risco-platform#3]
Hi,

First, i would like to thank you about your job on this plugin. I dreamed about control my "output" with homekit for a long time before you actually did this ! 

So ... Thanks a lot, your work is really appreciated ! 

All works fine but sometimes when i update the plugin or when i set something different on my "Partition" (in the JSON) i usually have this issue.

Is annoying because i need to restart homebridge and setup again the names on homekit. I already update today but i had the same issue on launch.

Maybe can you help ?

Here you can find my log ans my config.json for your plugin

Full error in logs :

[2020-6-26 15:18:26] [RiscoAlarm] Error on Get Partitions States : TypeError: Cannot read property 'type' of undefined
(node:30836) UnhandledPromiseRejectionWarning: undefined
(node:30836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)

Config.JSON :

{
            "platform": "RiscoAlarm",
            "name": "RiscoAlarm",
            "riscoUsername": "*************",
            "riscoPassword": "************",
            "riscoSiteId": ******,
            "riscoPIN": "****",
            "polling": true,
            "pollInterval": 10000,
            "Partition": "all",
            "Outputs": "all",
            "Detectors": "none"
        },

PS : Sorry for my crappy english, i'm from belgium and french is my native language.

**Comment by gawindx** [comment]
Bon, alors on va gagner du temps, je suis français donc dans mon cas aussi l'anglais n'est pas mon fort (merci google)...

Si je comprend bien, lorsque tu redémarres homebridge, c'est comme ci la config revenait à zéro ?
Dans ce cas, c'est que ton fichier config.json contient une anomalie dans sa structure (une virgule en trop ou manquante par exemple). J'ai eu le cas lors d'une mise à jour du container homebridge il n'y a pas longtemps alors que mon fichier de config passait avec la version précédente.

Pour l'erreur rencontrée, c'est un bug aléatoire pour lequel je n'ai pas encore trouvé de parade efficace.
Il semble que de manière aléatoire la requête pour récupérer les informations de partition aboutissent par un résultat incomplet de la part du RiscoCloud et dans ce cas de figure, le script se retrouve avec une valeur nulle...
Et comme c'est une réponse incorrect aléatoire, je galére un peu pour mettre le doigt dessus et contourner le problème.
Mais je vais finir par y arriver (tôt ou tard).

Dans ce cas, il y'a pas 36 solutions, il faut redémarrer homebridge.

**Comment by Sylanorr** [comment]
Haha excellent ! 

Merci pour ta réponse rapide du coup et encore bravo pour cet excellent travail ! J'attendais vraiment les fonctionnalités que tu proposes depuis une plombe ! 

Déjà, je suis rassuré par le fait que tu me dises que cela ne vient pas de moi mais qu'il s'agit bel et bien d'un bug aléatoire.

Plus précisément, lorsque l'erreur survient et que j'effectue le redémarrage d'homebridge, il me redétecte correctement mes partitions ainsi que mes outputs , mais dans homebridge il considère que c'est de nouveaux ajouts, et je dois donc manuellement les renommer et les replacer dans le groupe adéquat. J'espère que c'est plus clair ?

Donc tu me dis qu'il s'agit d'une erreur dans mon fichier de config et qu'en le corrigeant homekit devrait garder mes accessoires risco enregistrés sous leurs noms corrects c'est bien ça ?

Merci d'avance pour ta réponse.

**Comment by gawindx** [comment]
pour cette partie la je l'avais pas compris comme ça.
LEs accessoires ne sont pas permanents MAIS leur UUID est calculée en se basant sur :
- l'ID
- le type d'accessoires (detecteurs/sorties/Partitions/groups, etc..)
- le libelle de l'accessoire

Ce qui veux dire que, normalement, d'un démarrage à l'autre, l'UUID doit être le même.

Et je viens de vérifier de mon côté, aussi bien sur Homekit que sur l'interface Web de Homebridge, je n'ai pas de souci de ce genre.
Quelle version du plugin config-ui-x as tu ? je suis sur la 4.23.0

**Comment by Sylanorr** [comment]
Je suis sur la 4.23.1 (dernière release aujourd'hui je pense).
Je vais creuser de mon coté et voir si ça vient d'une config de ma part.

Merci pour ton aide.

**Comment by gawindx** [comment]
ah, j'avais pas vu la mise à jour mais je vais peut etre attendre un peu alors...

**Comment by gawindx** [comment]
Bon, je me suis pris la tête pendant plus d'une heure pour réussir a reproduire le bug aléatoire et savoir quelle était la réponse incorrect.
Je pense que j'ai mis en place une routine qui devrait fonctionner pour s'assurer que la réponse attendu est valide donc cela ne devrait plus apparaître.
Le plugins est mis à jour en 1.05 et contient le correctif.

**Comment by Sylanorr** [comment]
Hello ! 

Je viens de mettre à jour et de faire quelques tests ... Et bien, je pense que tu as su résoudre le problème car je n'ai plus expérimenté l'erreur en tentant malgré de jouer avec mes config RISCO et le reproduire (changement de types de partitions, passage en ALL, en SYSTEM, etc.).

De plus, comme la MAJ s'est faite sans encombre de mon coté, malgré le redémarrage d'homebridge, mes périphériques RISCO sont restés nommés pareil dans Homekit ! 

Je pense donc que c'est donc bien cette erreur qui produisait la perte des infos liées aux noms dans Homekit.

Encore une fois merci et bravo, je peux clôturer le post si tu veux ou on attend un peu ?

**Comment by gawindx** [comment]
Je pense que c’est résolu aussi
Je rechignais à me pencher sur ce problème mais au final, je crois que la fonction que j’ai mis en place va assurer que les réponses aux requêtes soient toujours correctes, qu’elle que soit la requête
Mais de toute façon il aurait fallu que je m’y colle à un moment ou un autre
Je clos et on rouvrira si besoin

**Comment by gawindx** [comment]
Bon,
Il semble que la modification soit fonctionnelle mais qu’elle engendre une boucle sans fin au bout d’un certain temps de fonctionnement (je pense que lorsque la session se déconnecte, la boucle se déclenche)
Seul moyen pour en sortir, redémarrer homebridge
Je retravaille dessus demain pour améliorer ça 
Et du coup je réouvre l’issue

**Comment by gawindx** [comment]
Cela semble être résolu.
4h de fonctionnement sans aucune boucle sans fin.
J'ai mis à jour en 1.0.8 et j’espère que cette fois cela sera Ok
J'attend quelques jours avant de fermer l'issue, histoire d’être sur que tout se passe bien

**Comment by Sylanorr** [comment]
Je mets à jour immédiatement et je te donnerais un retour d'ici 24h.
Merci pour ton travail.

**Comment by Sylanorr** [comment]
Le retour aura été plus long, mais voici 3 jours que ça tourne et aucun bugs de mon coté !

**Comment by gawindx** [comment]
Pareil de mon côté, ça semble être stable dans la durée.
Je ne dis pas que ce symptôme n’apparaîtra plus du tout mais maintenant j'aurai des infos a cet endroit du code pour compléter la gestion de l'erreur.

Je ferme l'issue
