### ISSUE TITLE
Error on Create Accessory Phase : %sTypeError: Cannot read property 'getCharacteristic' of undefined

### ISSUE THREAD

**Issue by Sylanorr** [gawindx/homebridge-risco-platform#30]
Hi,

Did someone already get this error ? 
Since a few days, Homebridge can't retrieve at all my partitions, i already had this error on the log. 
The Outputs are ok, but not the rest.

Here is the error i had on the log and my config.JSON

[2020-11-29 9:17:00] [RiscoAlarm] Error on Create Accessory Phase :
%sTypeError: Cannot read property 'getCharacteristic' of undefined

JSON : 

{
    "platform": "RiscoAlarm",
    "name": "RiscoAlarm",
    "riscoUsername": "XXXXX@gmail.com",
    "riscoPassword": "XXXXXXXXXXX",
    "riscoSiteId": XXXXXXX,
    "riscoPIN": "XXXX",
    "OccupancyPreventArming": false,
    "polling": false,
    "pollInterval": 10000,
    "armCommand": "armed",
    "partialCommand": "partially",
    "homeCommand": "disarmed",
    "disarmCommand": "disarmed",
    "Partition": "all",
    "Outputs": "all",
    "Detectors": "none"
}

**Comment by gawindx** [comment]
Hi,

I know that we could communicate in French but if you are not the only one to encounter this problem, it is preferable that we exchange in English.

Are you on the last version (1.2.0) released yesterday officially?
if not, start with its update.

if the problem still exists after updating, or if you already have the correct version, you should enable debug mode in homebridge. This should give a little more information on the accessory that is causing the problem.

as a last resort, have you tried to delete the accessory cache in homebridge to see if the problem is with an already existing accessory or not?

**Comment by jbreggeman** [comment]
same here, I reverted back to v1.1.0 as this one is not working somehow. not sure why

**Comment by gawindx** [comment]
@jbreggeman  
Be careful with version 1.1.0, it's an old version and there has been a lot of modification since.

@jbreggeman  & @Sylanorr 
Regarding the problem encountered, I will need more info than that to understand where it can come from.
Not that I don't know at what level this command is located in the code, but it is about a command executed for each accessory during its creation / restoration; so for once, I'm not a medium ...

And since I am not having this problem on my end, I cannot unblock it without info.

Incidentally, v1.2.1 is released and corrects an error when checking occupancy

**Comment by Sylanorr** [comment]
Hi,

I work with the last 1.2.1 Version
I delete the cache for all accessories but the issue is the same

With the Debug activate, I had this : 

[2020-11-29 23:18:52] [RiscoAlarm] Adding new accessory with Name: CM REZ DE CH+DET, Id: 0, type: Partitions
[2020-11-29 23:18:52] [RiscoAlarm] AddOrConfigure Accessory: CM REZ DE CH+DET
[2020-11-29 23:18:52] [RiscoAlarm] Error on Create Accessory Phase :
%sTypeError: Cannot read property 'getCharacteristic' of undefined
[2020-11-29 23:18:52] [RiscoAlarm] Accessories Init Phase Ended

The outputs are ok and works very well, the problem is just with the Partitions

I hope it will help.

Thank you for your help

**Comment by gawindx** [comment]
I think this will help.
already, this allows me to locate more precisely where it gets stuck.

I would test tomorrow with the same partition name as you, I suspect the '+' character is a problem.

@jbreggeman,  can you also activate the debug on homebridge and communicate to me the relevant lines of your logs (the name of the partition could be interesting if it contains a special character).

**Comment by Sylanorr** [comment]
@gawindx : Hi ! Any news about this issue ? Thanks

**Comment by gawindx** [comment]
to be frank, and contrary to what I thought, I have not yet had the time to carry out the tests, my job not having left me any personal time to devote to it.

At the latest, I will be able to test on Saturday or Sunday.

**Comment by Sylanorr** [comment]
Merci pour ta réponse rapide gawindx.
Cumulant un job, une femme enceinte et des cours du soirs , je comprends parfaitement le manque de temps pour un projet privé.

Je tiens à te remercier pour ta réactivité , ton projet est vraiment du bon boulot.

A bientôt 👍

**Comment by gawindx** [comment]
Je n'ai pas réussit à reproduire l'erreur que tu rencontre; en tout cas, cela ne vient pas d'un caractère dans le nom de la partition.
J'ai donc prit le problème autrement et j'ai modifié un peu le code de la fonction.
Au passage, j'ai amélioré la gestion de la reconnexion au RiscoCloud dans le cas de coupure réseau (j'ai pas une connexion exceptionnelle, mais pour le coup ça me permet de rencontrer des cas de figure inhabituel).

J'ai donc publié la v1.2.2 qui contient ces différents correctifs, si tu peux me faire un retour après l'avoir testé.

**Comment by Sylanorr** [comment]
Bonjour Gawindx,

J'ai bien mis à jour en V.1.2.2, mais j'ai toujours le même problème :( 

Je ne comprends pas ce qui peut provoquer cela. Cela marchait très bien dans les versions précédentes et avant la grosse mise à jour d'IRisco.

Bonne journée

**Comment by gawindx** [comment]
C’est d’autant plus surprenant que j’ai peu de retour de ce problème, donc tout le monde n’est pas touché.
Est ce que tu peux me donner un peu plus d’info sur les versions :
- de homebridge
- de node.js
- de npm
- sur quoi tu le fais tourner (Linux/Mac/Windows/raspberry pi, etc...)

As tu essayé en supprimant le cache de tes accessoires?(rien n’empêche de faire un backup avant pour éviter de perdre ta config)

**Comment by Sylanorr** [comment]
Bien sûr 👍 !

Voici : 

OS : Raspbian (Raspberry Pi 3)
Homebridge Version | v1.2.3
Version de Node.js | v12.18.3
Version de Npm | v6.14.6

J'ai supprimé le cache et réinitialiser tout ce qui était possible d'être réinitialisé sans succès.

**Comment by gawindx** [comment]
@Sylanorr, @jbreggeman 

I finally figured out how to reproduce the problem.
Version 1.2.3 must fix this

**Comment by Sylanorr** [comment]
And it works fine without any problem since I upgraded on 1.2.3 :) !
Thank you ! 👍

**Comment by jbreggeman** [comment]
Just upgrade too. Works great again!

Op zo 6 dec. 2020 om 20:28 schreef Sylanor <notifications@github.com>

**Comment by gawindx** [comment]
Ok, so we can consider the issue to be resolved
