### ISSUE TITLE
Is it possible to get a detector signaling when the alarm is disarmed?

### ISSUE THREAD

**Issue by jbreggeman** [gawindx/homebridge-risco-platform#32]
I would like to understand if it's possible to get a detector activate or signal in Homekit without having to arm the system. Is that possible?

**Comment by gawindx** [comment]
If I understand your question correctly, do you want to receive an information (notification?) When a detector is activated / deactivated without having to arm a partition?

If it is, then the plugin does not.
In fact it is a native function of the Home application.
Just go to settings, then you should see a list of device type.
When you go to the type of device, you will have the list of accessories that belong to it and you will be able to select the one or those for which you want or not to receive a notification.

**Comment by jbreggeman** [comment]
Hi, not entitle sure. I guess it would be nice to have the detectors act as
a motion detector that when someone enters a room with an active detector
without the system being armed, then it sends a signal to the app. Would
that be possible?


Op ma 7 dec. 2020 om 18:59 schreef Decaux Nicolas <notifications@github.com>

**Comment by gawindx** [comment]
This is exactly what the Home app does when you activate notifications on an accessory.

The accessory is activated, you receive a notification.
The accessory is deactivated, you receive a notification.

And to have activated it on several, it is even sometimes boring.

**Comment by jbreggeman** [comment]
Thanks for the explanation. It doesn’t seem to work with me. I see all the
sensors, but they don’t detect anything unless I arm the alarm. Any
thoughts?



Op ma 7 dec. 2020 om 19:57 schreef Decaux Nicolas <notifications@github.com>

**Comment by andyblac** [comment]
imo motion sensors in risco in homekit are a waste of time, the cloud is just to slow to detect a change. even contact sensor can take 2 mins to detect a state change, i gave up on them and just removed them from homekit.

**Comment by gawindx** [comment]
That, I wouldn't say the opposite.
In fact, it is very random.
The feedback is sometimes very fast, and sometimes very slow.

I think that the panel does not immediately transmit the changes but that it does it cyclically.
So if you activate the detector shortly before it transmits, we quickly get the info, otherwise ...

During my tests, sometimes I have to activate a detector for more than a minute to retrieve the info both via homebridge and on iRisco and sometimes I retrieve the info almost as soon as it is active.

Overall, I noticed the iRisco API is still a bit faster than the web interface for detectors.
And what about partitions / groups is much faster.

Coming back to the basic subject, notifications are active on most of my detectors and I have the notifications when they activate and deactivate.
Check your configuration in the Home app, you may have missed a step.

**Comment by gawindx** [comment]
Watch this
https://support.apple.com/en-us/HT208939

**Comment by jbreggeman** [comment]
I tried everything but these detectors do not seem to do any detection in the homekit app when disarmed. not sure what i am doing wrong.

**Comment by gawindx** [comment]
As I said, it sometimes takes a long time for the status of a detector to be transmitted.
But I think I was not specific enough:
when I speak of the state, it is not only to have made a detection on a detector but to maintain this detection.
I mean by that that sometimes you have to stay moving in front of the detector for 2 min to have a change.
And sometimes just walking past a few seconds is enough.

If you have the iRisco app, see if your detectors change state on it.
If you see the movements on it, you should also see them on Homekit.
If you have a magnetic contact on a door, do the test with this sensor leaving the door open, it will be easier than with a detector.


just a guess, is your system old? If so, it may be a firmware problem.
And what model do you have?
Agility 2/3/4? Lightsys? Prosys Plus?

Have you tried to re-pair homebridge with the Home app?
it may be necessary:
- remove the homebridge from the home app
- optionally delete the 'persist' directory in the Homebridge directory (for that I let you search if ever it is necessary)
- completely restart the Homebridge server or service (In general, when I do my tests and have to re-pair, it will fail if I do not perform this step).

**Comment by jbreggeman** [comment]
Hi thanks for the info. I actually found out that e sensor works but only
when the system is (partially) armed. It doesn’t do anything if it’s not
armed.

I think I have agility V2 or v3



Op ma 7 dec. 2020 om 23:25 schreef Decaux Nicolas <notifications@github.com>

**Comment by gawindx** [comment]
It seems logical then.

You must be on an old firmware version, so I'm not sure the detectors are still being transmitted.

Another important point: to save batteries, the radio detectors only change state every 1min30, except when they are armed ... (or when they are configured in fast mode but this mode is to be used only for system or maintenance tests and must be activated for each detector by going to the programming menu).

I think that explains that the state is not transmitted if they are not armed.

**Comment by jbreggeman** [comment]
Hi

Thanks for this. It seems to work now... but it’s very slow indeed... not
really workable for a quick update if you are want to detect something. But
thanks for the help

Op di 8 dec. 2020 om 00:03 schreef Decaux Nicolas <notifications@github.com>

**Comment by gawindx** [comment]
Sorry that the operation is not perfect with your system.

I think you won't mind if I close the issue.
