### ISSUE TITLE
Discovered 0 partitions

### ISSUE THREAD

**Issue by JLafranca** [gawindx/homebridge-risco-platform#33]
Dear reader,

thank you so much for writing this plugin. Would be wonderful if I can get it to work.

The problem I have is that there are no partitions detected according to the homebridge log. When I log in on the Risco site, I see my two partitions, so that's weird.

[12/13/2020, 12:50:43 PM] [Lafranca] Accessories Init Phase Started
[12/13/2020, 12:50:43 PM] [Lafranca] Discovering Phase Started
[12/13/2020, 12:50:43 PM] [Lafranca] Cloud Authentication Successfull
[12/13/2020, 12:50:43 PM] [Lafranca] Retrieving Cloud Session: Ok
[12/13/2020, 12:50:43 PM] [Lafranca] Discovered 0 Partitions
[12/13/2020, 12:50:43 PM] [Lafranca] Discovering Phase Ended
[12/13/2020, 12:50:43 PM] [Lafranca] PreConf Phase Started
[12/13/2020, 12:50:43 PM] [Lafranca] PreConf Accessory => Add Partitions
[12/13/2020, 12:50:43 PM] [Lafranca] PreConf Phase Ended
[12/13/2020, 12:50:43 PM] [Lafranca] Create Accessory Phase Started
[12/13/2020, 12:50:43 PM] [Lafranca] Accessories Init Phase Ended

Could you point me in the right direction? I am running HomeBridge 1.2.4 on a Synology NAS

Thanks in advance,

Best wishes,
Jeff

**Comment by gawindx** [comment]
Can you give me your config file (without your sensitive information)?

**Comment by JLafranca** [comment]
Certainly, as below:

{
    "platform": "RiscoAlarm",
    "name": "XX",
    "riscoUsername": "XX@XX.XX",
    "riscoPassword": "XXX",
    "riscoSiteId": XXXXX,
    "riscoPIN": "XXX",
    "armCommand": "ingeschakeld",
    "partialCommand": "gedeeltelijk",
    "disarmCommand": "uitgeschakeld",
    "partition": "all"
}

**Comment by gawindx** [comment]
2 things :
- the partition option normally starts with a capital letter so: "Partition": "all" instead of "partition": "all"
- for custom commands, I'm not sure it works if the commands are not in English (in any case I haven't tested it on my side so I'm not sure it works)

**Comment by JLafranca** [comment]
Thank you so much, I got it to work! Will be finetuning coming days. 

Wonderful integration. Will donate!

**Comment by gawindx** [comment]
Thank you for your support.

I do not close the issue, the problem you encountered is a bug (probably a regression generated by recent code evolutions).
In your case, without specifying a configuration for the Partition option (taking into account the lowercase error, this is equivalent to not defining the option), the plugin should have considered the "system" mode for the partitions.
You should therefore have recovered a unique accessory being a synthesizer of the existing Partition(s) on your installation.

So I'm tagging the issue as a bug and will fix it in a future update.

**Comment by gawindx** [comment]
Problem corrected in version 1.2.4
