### ISSUE TITLE
Error 422

### ISSUE THREAD

**Issue by gnoto** [gawindx/homebridge-risco-platform#35]
At start-up I receive the following messages:

[26/12/2020, 16:08:23] [Beethoven Alarm] Accessories Init Phase Started
[26/12/2020, 16:08:23] [Beethoven Alarm] Discovering Phase Started
[26/12/2020, 16:08:24] [Beethoven Alarm] Cloud Authentication Successfull
[26/12/2020, 16:08:24] [Beethoven Alarm] **Error 422
null**
[26/12/2020, 16:08:24] [Beethoven Alarm] Discovering Phase Ended
[26/12/2020, 16:08:24] [Beethoven Alarm] **Error on Discovery Phase : No Accessory Discovered**
[26/12/2020, 16:08:24] [Beethoven Alarm] PreConf Phase Started
[26/12/2020, 16:08:24] [Beethoven Alarm] PreConf Phase Ended
[26/12/2020, 16:08:24] [Beethoven Alarm] Create Accessory Phase Started
[26/12/2020, 16:08:24] [Beethoven Alarm] Accessories Init Phase Ended

My config is the following:

{
            "platform": "RiscoAlarm",
            "name": "Beethoven Alarm",
            "riscoUsername": "xxxx",
            "riscoPassword": "xxxx",
            "riscoSiteId": xxxx,
            "riscoPIN": "xxxx"
        }

Any idea?

**Comment by gawindx** [comment]
for the error 422, I do not see, I did not have the right to it yet during the development.

for the fact that it does not find anything, try by defining at least in element (partitions / groups / outputs / detector)
if you just want to arm / disarm, try with:
"Partition": "system" to manage all partitions as a single entity or
"Partition": "all" to recover each partition independently

**Comment by gnoto** [comment]
Unfortunately I always get the same error.
I did several tests, the last one with the following configuration:

{
            "platform": "RiscoAlarm",
            "name": "Beethoven Alarm",
            "riscoUsername": "g.noto@icloud.com",
            "riscoPassword": "082607",
            "riscoSiteId": 40000002242,
            "riscoPIN": "082607",
            "Partition": "all",
            "Groups": "none",
            "Outputs": "all",
            "Detectors": "all"
        }

But I always get the error "Error 422 null "and" Error on Discovery Phase: No Accessory Discovered "

**Comment by gawindx** [comment]
I took note of your message but for security concerns I deleted it.

Even edited, it is possible to go back to the original message and I don't know if I am the only one able to do it in this repository so in doubt ...

be more vigilant when posting sensitive information.

**Comment by gnoto** [comment]
You are right!
I’m very sorry and grateful to you.

Tnx

**Comment by gnoto** [comment]
Solved.
I had a wrong digit in the riscoSiteId

**Comment by gawindx** [comment]
it's interesting
I will have to test this, it will add a more explicit error message in this case.

I leave the issue open until this improvement is addressed.

**Comment by arturlukosek** [comment]
@gawindx 
Unfortunately have same issue as above. What is the minimum requirement to setup? 
Currently my json looks like below:
{
    "platform": "RiscoAlarm",
    "name": "Home Alarm",
    "riscoUsername": "my user name",
    "riscoPassword": "my password",
    "riscoSiteId": "site id",
    "riscoPIN": pin,
    "OccupancyPreventArming": true,
    "polling": true,
    "pollInterval": 10000,
    "Partition": "system"
}

**Comment by baz18** [comment]
Hi, I have the same problem described by gnoto
[3/19/2021, 5:30:09 PM] [RiscoAlarm] Accessories Init Phase Started
[3/19/2021, 5:30:09 PM] [RiscoAlarm] Discovering Phase Started
[3/19/2021, 5:30:10 PM] [RiscoAlarm] Cloud Authentication Successfull
**[3/19/2021, 5:30:10 PM] [RiscoAlarm] Error 422
null**
[3/19/2021, 5:30:10 PM] [RiscoAlarm] Discovering Phase Ended
**[3/19/2021, 5:30:10 PM] [RiscoAlarm] Error on Discovery Phase : No Accessory Discovered**
[3/19/2021, 5:30:10 PM] [RiscoAlarm] PreConf Phase Started
[3/19/2021, 5:30:10 PM] [RiscoAlarm] PreConf Phase Ended
[3/19/2021, 5:30:10 PM] [RiscoAlarm] Create Accessory Phase Started
[3/19/2021, 5:30:10 PM] [RiscoAlarm] Accessories Init Phase Ended


here is my config, btw it worked ok on a previous hoobs configuration, but now I switched to homebridge and I get error 422

{
    "platform": "RiscoAlarm",
    "name": "RiscoAlarm",
    "polling": true,
    "pollInterval": 15000,
    "riscoUsername": "xxxx",
    "riscoPassword": "xxxx",
    "riscoSiteId": xxxx,
    "riscoPIN": "xxxx",
    "OccupancyPreventArming": true,
    "armCommand": "armed",
    "partialCommand": "partially",
    "homeCommand": "disarmed",
    "disarmCommand": "disarmed",
    "Partition": "system"
}

thanks in advance for your help

**Comment by gawindx** [comment]
it is an identification error during the second connection phase to RiscoCloud.

At this stage, only 2 pieces of information are exchanged:
- The SiteID
- The pin code

so it is most likely an error on one of these two values.

The last version should have given more precise information but it seems that I left an error in the handling of this error code and therefore it is not clearly indicated in the logs.

**Comment by baz18** [comment]
> it is an identification error during the second connection phase to RiscoCloud.
> 
> At this stage, only 2 pieces of information are exchanged:
> 
> * The SiteID
> * The pin code
> 
> so it is most likely an error on one of these two values.
> 
> The last version should have given more precise information but it seems that I left an error in the handling of this error code and therefore it is not clearly indicated in the logs.

Thank you, I manually typed the siteId again and it is working correctly now

**Comment by gawindx** [comment]
Problem corrected in version 1.2.4 (1.2.5 for the wrong error code) to take into account error 422 and display an appropriate error code.
