### ISSUE TITLE
Suggestion: Exclude sensor

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-platform#38]
can we change the way excludes switch in homekit works atm when switch is ON the sensor is enabled, but this has the result that the switch in iOS always shows the switch as ON in the room banner.

Can we make it so if the Sensor is Excluded, the switch is ON, this would make more sense IMO as you can quickly see if the sesnor is excluded and it would stop the room banner getting cluttered.

Thanks
Andy.

**Comment by gawindx** [comment]
it is clearly possible.

I add it in my notes for when I have time.

**Comment by andyblac** [comment]
thx

**Comment by andyblac** [comment]
not woring correctly my home app keeps show as ON in top status bar, sometime as i open home app they briefly show ON them goes off, but lately there are not turning off.
