### ISSUE TITLE
don't work for me :(

### ISSUE THREAD

**Issue by ghost** [gawindx/homebridge-risco-platform#4]
hi,
I think I put all the things good.
but I can't run it...
Please help me :))

log:
6.7.2020, 12:37:20 [Home Alarm] Error on login : Error: Request failed with status code 200
6.7.2020, 12:37:21 [Home Alarm] Error on Discovery Partition : TypeError: Cannot read property 'parts' of null
6.7.2020, 12:37:22 [Home Alarm] Error on login : Error: Request failed with status code 200
6.7.2020, 12:37:22 [Home Alarm] Error: Bad HTTP Response : 302
    at RiscoPanelSession.DiscoverOutputs (/home/hoobs/.hoobs/node_modules/homebridge-risco-platform/Risco.js:694:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RiscoPanelPlatform.accessories (/home/hoobs/.hoobs/node_modules/homebridge-risco-platform/app.js:44:53)
6.7.2020, 12:37:22 [Home Alarm] Apply Custom Configuration
6.7.2020, 12:37:22 [Home Alarm] Modify Detectors to Door
6.7.2020, 12:37:22 [Home Alarm] Modify Detectors to Window
6.7.2020, 12:37:22 [Home Alarm] Discovering Phase Ended
6.7.2020, 12:37:22 [Home Alarm] AddAccessory Phase Started
6.7.2020, 12:37:22 [Home Alarm] Add Accessory => Add Partitions
6.7.2020, 12:37:22 [Home Alarm] Error on AddAccessory Phase : TypeError: Cannot read property 'type' of undefined
6.7.2020, 12:37:22 [Home Alarm] AddAccessory Phase Ended
6.7.2020, 12:37:22 [Home Alarm] Create Accessory Phase Started
6.7.2020, 12:37:22 [Home Alarm] Create Accessory Phase Ended
6.7.2020, 12:37:23 [Home Alarm] Accessories Init Phase Started

**Comment by gawindx** [comment]
Hello,

Without further information, I will do my best to guide you.
From the information you give me, it seems that the plugin cannot connect (1st error which generates the following errors - which makes me say at the same time that I should improve this phase of connection to not not go further in this case).

- Have you recovered your SiteID (from the RsicoCloud page, after entering your credentials, look on the README)
- Did you enter your connection information in the config.json file (look at the sample-config.json file or the README for more information)
- Does your password contain special characters which could be badly transmitted by the plugin?
- When you connect to a web page using riscocloud, do you have good access to your interface or does it not go as it should? (the plugin connecting via the RiscoCloud web interface, if you do not do it manually with your credentials, it will not do it automatically either - whether this is a problem with incorrect connection information or a problem with RiscoCloud himself)

can you copy me the contents of your config for verification (especially do not forget to delete the login and password - on the other hand if you use special characters for the password, tell me which ones, that I can test my side and see if it can come from there - in which case I will upgrade my code to make it work)

**Comment by gawindx** [comment]
Have you solved your problem?

Do you need more help or can I close the issue?

**Comment by ghost** [comment]
Hi!  Just yesterday I turned around to check again and there was a mistake with the siteID.  Now it works and even great!  Thank you!
