### ISSUE TITLE
Start alarm ?

### ISSUE THREAD

**Issue by szlaskidaniel** [gawindx/homebridge-risco-platform#43]
Do you think it is possible to execute alarm by some API call ? Trying to find some but failed on that.
Would be nice to to get API responsible to "fire the alarm", then this could be used with other sensors that could potentially start alarm.

**Comment by gawindx** [comment]
After some research and reflection, I don't think this is possible.
Well, not directly.

An alternative solution would be:
- have access to the porgrammation (and by extension to the installer mode of the system)
- wire an output of the control unit to an available input (this implies having an output and an input available, which means that on an 'Agility' type system, this is not possible without the X10 module which allows 4 output and wired input)
- configure this output to be controllable (code function assigned to the user)
- configure the input to correspond to the state of the output (normally open or closed, depending on the wiring and programming of the output)
- use this output via the "home" application to open a remote zone and thus trigger an alarm.

**Comment by gawindx** [comment]
This issue is closed due to the stop of the development of the plugin.
For more information, see [here](https://github.com/gawindx/homebridge-risco-platform/issues/45)
