### ISSUE TITLE
Simple Alarm in HomeKit

### ISSUE THREAD

**Issue by kev017** [gawindx/homebridge-risco-platform#6]
Hi there

Apologies, this is I suspect a question and not an issue but I couldn’t see how to ask a question.

I’ve a simple risco alarm with everything in one partition. Through the risco app, I only use Set to set the alarm and Unset to unset it. Now that I’ve added the alarm to HomeKit via this plug-in, how do the above statues translate to Home / Away / Night / Off that are shown for my partition? I assume that Off is Unset, would Away be Set?

**Comment by gawindx** [comment]
It's actually fairly easy :
- Off => disarm
- Home / Night => Partial (when the alarm is set but only the perimeter sensors are active and you can stay inside)
- Away => complete arming (away from home)

**Comment by kev017** [comment]
Thank you. 

Do you have a Patron or a means where I can buy you a coffee?

**Comment by gawindx** [comment]
a thank you is enough for me
But it's nice of you

**Comment by kev017** [comment]
Many thanks.
